# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settings.ui'
#
# Created: Sat Oct 20 20:11:44 2012
#      by: pyside-uic 0.2.13 running on PySide 1.1.1
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.resize(910, 556)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setStyleSheet("")
        self.verticalLayout = QtGui.QVBoxLayout(Settings)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.layout_outside = QtGui.QVBoxLayout()
        self.layout_outside.setObjectName("layout_outside")
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setEnabled(True)
        font = QtGui.QFont()
        font.setWeight(50)
        font.setUnderline(False)
        font.setBold(False)
        self.tabWidget.setFont(font)
        self.tabWidget.setMouseTracking(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"     border-top: 2px solid #C2C7CB;\n"
"     background-color:white;\n"
"\n"
" }\n"
" QTabWidget::tab-bar {\n"
"     alignment: left;\n"
"    background-color:#d9d9d9;\n"
"    \n"
" }\n"
"QTabBar::tab {\n"
"    height:35px;\n"
"    width:80px;\n"
"     background:#d9d9d9;\n"
"     border: 6px solid #d9d9d9;\n"
"     border-bottom-color: #d9d9d9; /* same as the pane color */\n"
"    padding:0px;\n"
"     min-width: 8ex;\n"
"    margin:0px;    \n"
"    font-size:18px;\n"
"    \n"
" }\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"     background:#b60400;\n"
"      color:white;\n"
" }\n"
"")
        self.tabWidget.setInputMethodHints(QtCore.Qt.ImhNone)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_8 = QtGui.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.paltformlistView = QtGui.QListView(self.tab)
        self.paltformlistView.setGridSize(QtCore.QSize(0, 20))
        self.paltformlistView.setObjectName("paltformlistView")
        self.gridLayout_8.addWidget(self.paltformlistView, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_8.addItem(spacerItem, 0, 3, 1, 1)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.path_line = QtGui.QLineEdit(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.path_line.setFont(font)
        self.path_line.setObjectName("path_line")
        self.gridLayout.addWidget(self.path_line, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.time_spinbox = QtGui.QSpinBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.time_spinbox.setFont(font)
        self.time_spinbox.setMinimum(1)
        self.time_spinbox.setObjectName("time_spinbox")
        self.gridLayout.addWidget(self.time_spinbox, 1, 1, 1, 1)
        self.autoslide_checkbox = QtGui.QCheckBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.autoslide_checkbox.setFont(font)
        self.autoslide_checkbox.setText("")
        self.autoslide_checkbox.setObjectName("autoslide_checkbox")
        self.gridLayout.addWidget(self.autoslide_checkbox, 0, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 2, 0, 1, 1)
        self.chooseButton = QtGui.QPushButton(self.tab)
        self.chooseButton.setObjectName("chooseButton")
        self.gridLayout.addWidget(self.chooseButton, 2, 2, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout, 0, 1, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab)
        self.label_20.setObjectName("label_20")
        self.gridLayout_8.addWidget(self.label_20, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.FieldsStayAtSizeHint)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setObjectName("formLayout")
        self.label_9 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_9)
        self.feedbackTextEdit = QtGui.QPlainTextEdit(self.tab_2)
        self.feedbackTextEdit.setObjectName("feedbackTextEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.SpanningRole, self.feedbackTextEdit)
        self.label_12 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_12)
        self.userinfolineEdit = QtGui.QLineEdit(self.tab_2)
        self.userinfolineEdit.setInputMask("")
        self.userinfolineEdit.setText("")
        self.userinfolineEdit.setObjectName("userinfolineEdit")
        self.formLayout.setWidget(6, QtGui.QFormLayout.SpanningRole, self.userinfolineEdit)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.postUpButton = QtGui.QPushButton(self.tab_2)
        self.postUpButton.setObjectName("postUpButton")
        self.horizontalLayout_3.addWidget(self.postUpButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.formLayout.setLayout(8, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_3)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.cleanLabel = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cleanLabel.sizePolicy().hasHeightForWidth())
        self.cleanLabel.setSizePolicy(sizePolicy)
        self.cleanLabel.setCursor(QtCore.Qt.PointingHandCursor)
        self.cleanLabel.setObjectName("cleanLabel")
        self.horizontalLayout_4.addWidget(self.cleanLabel)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_4.addWidget(self.label_17)
        self.limitLabel = QtGui.QLabel(self.tab_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.limitLabel.sizePolicy().hasHeightForWidth())
        self.limitLabel.setSizePolicy(sizePolicy)
        self.limitLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.limitLabel.setObjectName("limitLabel")
        self.horizontalLayout_4.addWidget(self.limitLabel)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.formLayout.setLayout(3, QtGui.QFormLayout.SpanningRole, self.horizontalLayout_4)
        self.gridLayout_7.addLayout(self.formLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtGui.QLabel(self.tab_3)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/source/aboutlogo.png"))
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 0, 2, 1, 1)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_16 = QtGui.QLabel(self.tab_3)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_3.addWidget(self.label_16)
        self.label_11 = QtGui.QLabel(self.tab_3)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_3.addWidget(self.label_11)
        self.label_13 = QtGui.QLabel(self.tab_3)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setOpenExternalLinks(True)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_3.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.tab_3)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setOpenExternalLinks(True)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_3.addWidget(self.label_14)
        self.label_3 = QtGui.QLabel(self.tab_3)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setOpenExternalLinks(True)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_19 = QtGui.QLabel(self.tab_4)
        self.label_19.setAcceptDrops(False)
        self.label_19.setOpenExternalLinks(True)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout.addWidget(self.label_19)
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setOpenExternalLinks(True)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_5 = QtGui.QLabel(self.tab_4)
        self.label_5.setOpenExternalLinks(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem6)
        self.gridLayout_2.addLayout(self.horizontalLayout, 3, 2, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem7)
        self.label_4 = QtGui.QLabel(self.tab_4)
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/source/aboutlogo.png"))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 2, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 2, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.layout_outside.addWidget(self.tabWidget)
        self.verticalLayout.addLayout(self.layout_outside)

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.cleanLabel, QtCore.SIGNAL("linkActivated(QString)"), self.feedbackTextEdit.clear)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QtGui.QApplication.translate("Settings", "Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Settings", "自动切换壁纸：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Settings", "切换间隔(分钟):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("Settings", "下载目录：", None, QtGui.QApplication.UnicodeUTF8))
        self.chooseButton.setText(QtGui.QApplication.translate("Settings", "选择", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("Settings", "请在下面列表中选择您的桌面环境", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("Settings", "常规设置", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Settings", "您遇到问题了吗？赶紧反馈给我们吧", None, QtGui.QApplication.UnicodeUTF8))
        self.feedbackTextEdit.setPlainText(QtGui.QApplication.translate("Settings", "您遇到了什么问题？在什么时候？做什么操作？", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("Settings", "您的联系方式，有可能获得惊喜哟...", None, QtGui.QApplication.UnicodeUTF8))
        self.userinfolineEdit.setPlaceholderText(QtGui.QApplication.translate("Settings", "手机号码.E-mail地址或者其他的信息", None, QtGui.QApplication.UnicodeUTF8))
        self.postUpButton.setText(QtGui.QApplication.translate("Settings", "提交", None, QtGui.QApplication.UnicodeUTF8))
        self.cleanLabel.setText(QtGui.QApplication.translate("Settings", "<html><head/><body><p><a href=\"http://clean.com\"><span style=\" text-decoration: underline; color:#0000ff;\">清空内容...</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_17.setText(QtGui.QApplication.translate("Settings", "还可以输入：", None, QtGui.QApplication.UnicodeUTF8))
        self.limitLabel.setText(QtGui.QApplication.translate("Settings", "500", None, QtGui.QApplication.UnicodeUTF8))
        self.label_18.setText(QtGui.QApplication.translate("Settings", "个字", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("Settings", "意见反馈", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("Settings", "<html><head/><body><p>版本:<span style=\" font-weight:600;\">1.5.1</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("Settings", " 官方QQ群：240059255", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("Settings", "<html><head/><body><p>官方网站：<a href=\"http://www.lovebizhi.com\"><span style=\" text-decoration: underline; color:#0000ff;\">http://www.lovebizhi.com</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("Settings", "<html><head/><body><p>联系我们：<a href=\"mailto:info@lovebizhi.com\"><span style=\" text-decoration: underline; color:#0000ff;\">info (at) lovebizhi.com</span></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Settings", "©北京取道兴业有限公司", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("Settings", "关于", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Settings", "<html><head/><body><p><a href=\"http://lovebizhi.com/iphone.html\"><img src=\":/source/button-iphone.png\"/></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_19.setText(QtGui.QApplication.translate("Settings", "<html><head/><body><p><a href=\"http://lovebizhi.com/ipad.html\"><img src=\":/source/ipad.png\"/></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Settings", "<html><head/><body><p><a href=\"http://lovebizhi.com/wp.html\"><img src=\":/source/button-wp7.png\"/></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Settings", "<html><head/><body><p><a herf=\"http://lovebizhi.com/android.html\"><img src=\":/source/button-android.png\"/></a></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("Settings", "<html><head/><body><p>爱壁纸HD不只有Linux版本，我们还提供了以下平台的版本供您选用</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("Settings", "客户端", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
import resources_rc
import resources_rc
